Distinguish between different outcomes

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -87,9 +87,12 @@ jobs:
 #          commit_author: zeitgeist-benchmark-bot <zeitgeist-benchmark-bot@no-reply.zeitgeist.pm>
 #          status_options: '--untracked-files=no'
       - name: Run benchmarks
+        id: run_benchmarks
         env:
           GITHUB_EVENT_NAME: ${{ github.event_name }}
         run: |
+          echo "::set-output name=error::'ERROR: Branch contains new commits. Aborting benchmarks.'"
+
           if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
             echo "triggered by dispatch"
           else
@@ -105,9 +108,21 @@ jobs:
           label: s:benchmark-required
           type: remove
       - name: Add label s:benchmark_done
-        if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 's:benchmark-required'))
+        if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 's:benchmark-required')) && [ -z ${{ steps.run_benchmarks.output.error }} ]
         uses: buildsville/add-remove-label@v1
         with:
           token: ${{secrets.GITHUB_TOKEN}}
           label: s:benchmark-done
           type: add
+      - name: Add label s:benchmark_aborted
+        if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 's:benchmark-required')) && [ -n ${{ steps.run_benchmarks.output.error }} ]
+        uses: buildsville/add-remove-label@v1
+        with:
+          token: ${{secrets.GITHUB_TOKEN}}
+          label: s:benchmark-aborted
+          type: add
+      - name: Exit with error message
+        if: [ -n ${{ steps.run_benchmarks.output.error }} ]
+        run: |
+          echo ${{ steps.run_benchmarks.output.error }}
+          exit 1
